version: "3.7"

services:
  typer_client:
    container_name: typer_client
    image: rsn11/typer_client:latest
    build:
      context: .
      labels:
        com.rsn.description: "Client for typer app"
        com.rsn.maintainer: "Rami Serapian"
    ports:
      - "8888:8080"
    volumes:
      - type: bind
        source: $PWD
        target: /var/www
