version: "3"
networks:
  typer:
services:
  typer_client:
    image: rsn11/typer_client
    volumes:
      - ./dist:/var/www/html:rw
    networks:
      - typer
    ports:
      - "82:80"
  # typer_server:
  #   container_name: typer_server
  #   image: python:3
  #   ports:
  #     - "5000:5000"
